### ISSUE TITLE
Improvement notes

### ISSUE THREAD

**Issue by haixuanTao** [EricLBuehler/pyo3-special-method-derive#13]
Really like current progress. Couple of format points:

- [x] Could we rename function procedural macros: `Dir` instead of `DirHelper`, `Str` instead of `StrHelper`. I know this is to help user display info, but I think it is quite inplicit that it is going to help in some ways.

- [x] Could we split `Str` and `Repr` as they are two distinct function in python.

- [x] Could we namespace the #[skip] in the likes of serde: https://serde.rs/attr-skip-serializing.html as it might create confusion when using multiple procedural macro. We can name it: `#[special_method(skip)]` or something else. See also: https://internals.rust-lang.org/t/add-skip-attribute-to-various-derives/17411/21

**Comment by EricLBuehler** [comment]
Thanks for the suggestions! I have implemented all of them, see the [example](https://github.com/EricLBuehler/pyo3-special-method-derive/blob/master/examples/all/main.rs).

**Comment by haixuanTao** [comment]
Thanks!

I wouldn't merge them together to be honest as it isn't really in the philosophy of rust. See: 

```rust
        #[derive(Eq, PartialEq, Ord, PartialOrd)]
```

or

```rust
#[derive(Add, Sub, Mul, Div, ..., Copy, Clone, Debug, Eq, PartialEq, Hash, Ord, PartialOrd)]
```

People in rust likes to be expressive.

But I also think it might be confusing to derive them all as there is so many special method in python that it could might be confusing in terms of expectation
