### ISSUE TITLE
Conflicting implementation of Debug and Display

### ISSUE THREAD

**Issue by haixuanTao** [EricLBuehler/pyo3-special-method-derive#24]
Could we make it so that we don't impl Debug and Display when deriving `Repr` and `Str` ?

The thing is that people might have a specific displayer or debugger?

We should probably expect them to implement Debug and Display, and maybe for some object, the custom display can remove the Option or the RwLock, to make it more pythonic. @ArthurZucker

**Comment by haixuanTao** [comment]
We could have additional derive method called PyDisplay an PyDebug that we can use to autogenerate Debug and Display that looks good.

**Comment by EricLBuehler** [comment]
Hi @haixuanTao, I think that that could be a good option. The only difficult part is actually generating the PyDisplay/PyDebug impl. Do you think it would be best to enforce that types inside of the struct/enum (recursively) implment PyDisplay/PyDebug trait by having a special method name?

**Comment by EricLBuehler** [comment]
Fixed in #26.
